### ISSUE TITLE
ExecutionQueue not public

### ISSUE THREAD

**Issue by lucashabersaat** [ethz-gtc/npc-engine#1]
Hi,

Little question / suggestion concerning the [ExecutionQueue](https://github.com/ethz-gtc/npc-engine/blob/main/npc-engine-utils/src/executor.rs#L142) in the *npc_engine_utils*.

Even though it is stated in the [comments](https://github.com/ethz-gtc/npc-engine/blob/main/npc-engine-utils/src/executor.rs#L140), that one could use the `ExecutionQueue` for custom executors, the struct is not accessible outside the crate, i.e. not public. I guess, this is an oversight, yes?

Further, for my project, I could use a getter for the `task_queue` field of the `ExecutorQueue`.

I would create a pull request on my own, I do not have any rights, though.

Best regards,
Lucas

**Comment by stephanemagnenat** [comment]
You are correct, the struct `ExecutionQueue` should be public. Can you do a small PR with this change?

**Comment by stephanemagnenat** [comment]
What would you wish to use the `task_queue` directly for? There is no getter at the moment because `ExecutionQueue` is fully encapsulating its `task_queue` (it is essentially a new type).

**Comment by lucashabersaat** [comment]
Ultimately, I'd like to test, whether a certain task has been planned for.
However, I realise I should be able to use the hooks of the `ExecutorState`.

**Comment by lucashabersaat** [comment]
I created a pull request, #2

**Comment by stephanemagnenat** [comment]
Closed by #2.
