### ISSUE TITLE
Store/Load Learned

### ISSUE THREAD

**Issue by SergioRibera** [ethz-gtc/npc-engine#4]
It's probably already implemented, but I still feel like a guide or example is needed for explain how save and load previously learned

**Comment by stephanemagnenat** [comment]
Can you give some more context please? In general, there is no learning for NPC engine, as it is a state space search planner.

**Comment by SergioRibera** [comment]
> Can you give some more context please? In general, there is no learning for NPC engine, as it is a state space search planner.

Oh, it seems I have confused the purpose of the project, anyway thank you very much for your attention, my bad 😅

**Comment by stephanemagnenat** [comment]
No problem, feel free to close the issue if your question is answered!
